### ISSUE TITLE
Possible to release 3.8.2 with kar format

### ISSUE THREAD

**Issue by jonesbusy** [martinspielmann/nexus3-crowd-plugin#84]
Hi!

We are using Nexus3 and have implemented a custom Helm chart in order to configure Nexus as code.

We rely also on other bundle like PHP composer (https://github.com/sonatype-nexus-community/nexus-repository-composer) and would like to unify the way the Crowd plugin is installed.

In most recent version of Nexus3 (3.15 I think) it's way easier to install new bundle on Nexus3

I've tried to build locally the 3.8.2-SNAPSHOT using

```
mvn -PbuildKar package 
```

and dropped the 'nexus3-crowd-plugin-3.8.2-SNAPSHOT-bundle.kar' into the ${NEXUS_HOME}/deploy folder.

Works like a charm! And way easier to install. I've tested this setup on version OSS 3.27.0-03

![Screenshot from 2020-10-06 19-04-35](https://user-images.githubusercontent.com/825750/95236232-f64d0200-0806-11eb-8f50-99abdca6b6a8.png)

Can we release version 3.8.2 and ensuring the 'nexus3-crowd-plugin-3.8.2-bundle.kar' archive is attached to the github release ?

More information can be found here : https://github.com/sonatype-nexus-community/nexus-repository-composer

PS : I would be more than happy to submit a PR to update the README

Thanks!

Valentin

**Comment by martinspielmann** [comment]
Hi Valentin,
thanks for the hint! Yes lets do it. I'll wait for your PR and then do the release, ok?

**Comment by jonesbusy** [comment]
Sure! The PR is linked
